-- SQL script to create the 'users' table in 'userdb' database

create table if not exists users (
   id         int
      generated by default as identity
   primary key,
   email      varchar(255) not null unique,
   password   varchar(255) not null,
   firstname  varchar(100) not null,
   lastname   varchar(100) not null,
   age        int not null,
   gender     varchar(20) not null,
   state      varchar(100) not null,
   created_at timestamp default current_timestamp
);